openapi: "3.0.0"
info:
  version: 1.0.0
  title: tg bot
paths:
  /${bot_path}:
    post:
      operationId: ${bot_name}
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: ${function_id}
        service_account_id: ${service_account_id}
